# Site settings
title: Sem compromisso com a realidade
email:
description: > # this means to ignore newlines until "baseurl:"
  Wenn ist das Nunstruck git und Slotermeyer? Ja!...
  Beiherhund das Oder die Flipperwaldt gersput!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username: fhisamoto
delicious_user: fhisamoto
delicious_count: 5

# Build settings
markdown: kramdown

exclude: [vendor, bin, .bundle]